// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:9d67e93b-c0a6-4f69-bb7d-282fc03b5761",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_CHS3LWKTj",
    "aws_user_pools_web_client_id": "73g03n4em6jte6j3sn40e8of1m",
    "oauth": {}
};


export default awsmobile;
