// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:9d67e93b-c0a6-4f69-bb7d-282fc03b5761",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_CHS3LWKTj",
    "aws_user_pools_web_client_id": "73g03n4em6jte6j3sn40e8of1m",
    "oauth": {},
    "aws_cloud_logic_custom": [
        {
            "name": "documents",
            "endpoint": "https://rhjgngvuo3.execute-api.us-east-1.amazonaws.com/ahfront",
            "region": "us-east-1"
        }
    ],
    "aws_dynamodb_all_tables_region": "us-east-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "documents-ahfront",
            "region": "us-east-1"
        }
    ]
};


export default awsmobile;
